In [1]:
import sys
sys.path.append('..')
from luriegold import LurieGold
from illmat import illmat
import numpy as np

# Example - LurieGold class

Generate an ill-conditioned correlation matrix that might be discretionary created by subjective human expert opinions.

In [2]:
d = 4
R = illmat(d, random_state=2).round(2)
R

array([[ 1.  , -0.95,  0.1 , -0.13],
       [-0.95,  1.  , -0.59,  0.24],
       [ 0.1 , -0.59,  1.  ,  0.06],
       [-0.13,  0.24,  0.06,  1.  ]])

`LurieGold` wraps the function `luriegold` in a sklearn-ish API class.

In [3]:
obj = LurieGold()
C = obj.fit_transform(R)

In [4]:
print("C =\n", C.round(3))
print("\nIs Det(C)>=0 ?\n", np.linalg.det(C))
print("\nDiff =\n", np.abs(R-C).round(3))

C =
 [[ 1.    -0.886  0.129 -0.139]
 [-0.886  1.    -0.554  0.229]
 [ 0.129 -0.554  1.     0.055]
 [-0.139  0.229  0.055  1.   ]]

Is Det(C)>=0 ?
 4.0142817041466993e-10

Diff =
 [[0.    0.064 0.029 0.009]
 [0.064 0.    0.036 0.011]
 [0.029 0.036 0.    0.005]
 [0.009 0.011 0.005 0.   ]]


# Source

In [5]:
??LurieGold

Init signature: LurieGold()
Docstring:     
Base class for all estimators in scikit-learn

Notes
-----
All estimators should specify all the parameters that can be set
at the class level in their ``__init__`` as explicit keyword
arguments (no ``*args`` or ``**kwargs``).
Source:        
class LurieGold(BaseEstimator, TransformerMixin):
    def __init__(self):
        """No settings required"""

    def fit(self, X: np.ndarray, y: np.ndarray = None):
        """Do nothing and return the estimator unchanged"""
        return self

    def transform(self, X: np.ndarray) -> np.ndarray:
        C, _, _ = luriegold(X)
        return C
File:           ~/PkgDev/luriegold/luriegold/luriegold_class.py
Type:           type
